os:
  - linux
  - osx
  
language: rust

sudo: required

rust:
  - beta

before_script:
  - |
      sudo apt-get update -qq &&
      sudo apt-get install -qq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev &&
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only beta doc
after_success:
  - travis-cargo --only beta doc-upload
  - travis-cargo coveralls

env:
  global:
    secure: fCU0zX/BW0MlzTcIFtVI8Ipn69ECh7iix0YFZ01H2GTpQujOieyL2lFo92rlryNKxc5ghhvcBfIOLwO42LY+hO81RiMJm1mG+SSSK/S8q4Do+WIXZei2THUx1T8tNw0E5eUGVrncXITnTSqsTA9+2GLeyQKaoPtbaPf9nQkCr8I=
