[package]

name = "message_filter"
version = "0.1.0"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/message_filter/"
repository = "https://github.com/dirvine/message_filter"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
time = "*"
rand = "*"
